name: dartlang_playground

description: A dartlang playground.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  characters: ^1.0.0
  json_annotation: ^4.0.1

dev_dependencies:
  test: ^1.26.3
  build_runner: ^2.1.11
  json_serializable: ^6.11.1
  source_gen: ^4.0.1 # https://github.com/dart-lang/source_gen


# https://dart.cn/guides/language/analysis-options
analyzer:
  exclude:
    - lib/tour/libraries_and_visibility/using_libraries.dart
    - lib/tour/metadata/metadata.dart
